# Use Node.js
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app source (volume mount will overwrite this in dev)
COPY . .

# Expose React dev server port
EXPOSE 3000

# Start React in development mode
CMD ["npm", "start", "--watch-poll"]
